#openexchangerates.org
openexchangerates:
  url: https://openexchangerates.org/api
  your-id: dd19753a9ccb451fba84b58474cf5cb1
  currency: RUB

#giphy.com
giphy:
  url: https://api.giphy.com/v1/gifs/search
  api-key: ldgRqnBfvkg4ZtfwDuhm44BStP3hpCAu
  rich: rich
  broke: broke

#logger
logging:
  level:
    root: WARN
    com.pvasic.currencyratio: DEBUG

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true
